# Generated by Django 6.0.5 on 2026-06-11 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='알람 이름')),
                ('target_type', models.CharField(choices=[('single', '개별 호스트'), ('group', '호스트 그룹'), ('all', '전체 호스트')], default='single', max_length=20, verbose_name='대상 타입')),
                ('hostname', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='호스트명')),
                ('metric_source', models.CharField(max_length=50, verbose_name='메트릭 소스')),
                ('metric_field', models.CharField(max_length=100, verbose_name='메트릭 필드')),
                ('filter_key', models.CharField(blank=True, default='', max_length=50, verbose_name='필터 키')),
                ('filter_value', models.CharField(blank=True, default='', max_length=100, verbose_name='필터 값')),
                ('log_keyword', models.CharField(blank=True, default='', max_length=100, verbose_name='로그 키워드')),
                ('condition', models.CharField(choices=[('gt', '보다 큼 (> )'), ('lt', '보다 작음 (< )'), ('eq', '같음 (=)'), ('host_down', '호스트 오프라인')], max_length=20, verbose_name='조건')),
                ('threshold', models.FloatField(default=0.0, verbose_name='임계치')),
                ('severity', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('critical', '위험')], default='warning', max_length=20, verbose_name='심각도')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='웹훅 URL')),
                ('notification_email', models.CharField(blank=True, help_text='쉼표(,)로 구분하여 여러 이메일 지정 가능', max_length=500, null=True, verbose_name='알림 이메일')),
                ('cooldown_minutes', models.IntegerField(default=5, verbose_name='쿨다운(분)')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 발생 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '알람 규칙',
                'verbose_name_plural': '알람 규칙 목록',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='그룹 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '호스트 그룹',
                'verbose_name_plural': '호스트 그룹 목록',
            },
        ),
        migrations.CreateModel(
            name='ManagedServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='호스트명')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='닉네임')),
                ('last_detected_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='최근 감지 IP')),
                ('reachable_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='접속 IP')),
                ('retention_days', models.IntegerField(default=14, verbose_name='데이터 보존 기간(일)')),
                ('status_api', models.CharField(default='normal', max_length=20, verbose_name='API 상태')),
                ('status_ping', models.CharField(default='normal', max_length=20, verbose_name='Ping 상태')),
                ('last_ping_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 핑 시도 시각')),
                ('last_success_ping_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 핑 성공 시각')),
                ('last_success_api_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 API 성공 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '관리 서버',
                'verbose_name_plural': '관리 서버 목록',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, default='', max_length=100, verbose_name='호스트명')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='발생 당시 값')),
                ('severity', models.CharField(default='warning', max_length=20, verbose_name='심각도')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생 시각')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결 여부')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결 시각')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.alertrule', verbose_name='규칙')),
            ],
            options={
                'verbose_name': '알람 이력',
                'verbose_name_plural': '알람 이력 목록',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='패널 제목')),
                ('host', models.CharField(db_index=True, max_length=100, verbose_name='호스트')),
                ('parent_host', models.CharField(blank=True, default='', max_length=100, verbose_name='상위 호스트')),
                ('metric_source', models.CharField(max_length=50, verbose_name='메트릭 소스')),
                ('metric_field', models.CharField(max_length=100, verbose_name='메트릭 필드')),
                ('chart_type', models.CharField(default='text', max_length=20, verbose_name='차트 타입')),
                ('filter_key', models.CharField(blank=True, default='', max_length=50, verbose_name='필터 키')),
                ('filter_value', models.CharField(blank=True, default='', max_length=100, verbose_name='필터 값')),
                ('log_filter', models.CharField(blank=True, default='', max_length=100, verbose_name='로그 필터')),
                ('memo_content', models.TextField(blank=True, default='', verbose_name='메모 내용')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=2)),
                ('h', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대시보드 패널',
                'verbose_name_plural': '대시보드 패널 목록',
                'ordering': ['y', 'x'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='host_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_dashboard.hostgroup', verbose_name='대상 그룹'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='core_dashboard.managedserver', verbose_name='소속 서버'),
        ),
        migrations.CreateModel(
            name='MetricAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=100, verbose_name='호스트명')),
                ('source', models.CharField(db_index=True, max_length=100, verbose_name='소스')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='기간 시작')),
                ('period_end', models.DateTimeField(verbose_name='기간 종료')),
                ('agg_type', models.CharField(choices=[('avg', '평균'), ('max', '최대'), ('min', '최소')], max_length=10, verbose_name='집계 유형')),
                ('value', models.FloatField(null=True, verbose_name='값')),
                ('data', models.JSONField(default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '메트릭 집계',
                'verbose_name_plural': '메트릭 집계 목록',
                'indexes': [models.Index(fields=['hostname', 'source', 'period_start'], name='core_dashbo_hostnam_815b23_idx')],
                'unique_together': {('hostname', 'source', 'period_start', 'period_end', 'agg_type')},
            },
        ),
        migrations.CreateModel(
            name='MetricMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=100, verbose_name='호스트명')),
                ('source', models.CharField(db_index=True, max_length=100, verbose_name='소스')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='최근 감지 시각')),
                ('metadata', models.JSONField(default=dict, verbose_name='메타데이터')),
            ],
            options={
                'verbose_name': '메트릭 메타데이터',
                'verbose_name_plural': '메트릭 메타데이터 목록',
                'unique_together': {('hostname', 'source')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, default='unknown', max_length=100, verbose_name='호스트명')),
                ('source', models.CharField(db_index=True, max_length=100, verbose_name='소스')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='타임스탬프')),
                ('data', models.JSONField(verbose_name='데이터')),
                ('level', models.CharField(default='INFO', max_length=20, verbose_name='레벨')),
            ],
            options={
                'verbose_name': '모니터링 메트릭',
                'verbose_name_plural': '모니터링 메트릭 목록',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hostname', 'source', 'timestamp'], name='core_dashbo_hostnam_eafcb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataCollectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('linux', '리눅스 공통'), ('windows', '윈도우 공통'), ('custom', '서버 전용')], default='custom', max_length=20, verbose_name='설정 타입')),
                ('config', models.JSONField(default=dict, help_text='데이터 수집(메트릭/로그 저장 규칙)을 위한 JSON 설정', verbose_name='설정 JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_dashboard.managedserver', verbose_name='서버')),
            ],
            options={
                'verbose_name': '데이터 수집 설정',
                'verbose_name_plural': '데이터 수집 설정 목록',
                'unique_together': {('server', 'config_type')},
            },
        ),
    ]
